version: '3.8'

services:
  postgres:
    image: postgres:17-alpine
    container_name: carsharing-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1244ag
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - carsharing-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    container_name: carsharing-user-service
    ports:
      - "8082:8082"
    environment:
      - DB_HOST=postgres
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - carsharing-network

  fleet-service:
    build:
      context: ./fleet-service
      dockerfile: Dockerfile
    container_name: carsharing-fleet-service
    ports:
      - "8081:8081"
    environment:
      - DB_HOST=postgres
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - carsharing-network

  order-service:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    container_name: carsharing-order-service
    ports:
      - "8083:8083"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - USER_SERVICE_HOST=carsharing-user-service
      - FLEET_SERVICE_HOST=carsharing-fleet-service
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - carsharing-network

networks:
  carsharing-network:
    driver: bridge

volumes:
  pgdata: