server:
  port: 8081
spring:
  application:
    name: fleet-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/fleet_db
    username: postgres
    password: 1244ag
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect