server:
  port: 8083
spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/order_db
    username: postgres
    password: 1244ag
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
services:
  user:
    url: http://${USER_SERVICE_HOST:localhost}:8082/api/users
  fleet:
    url: http://${FLEET_SERVICE_HOST:localhost}:8081/api/cars